version: '3'

services:
  backend:
    build: ./BE
    container_name: fastapi-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./FE
    container_name: react-frontend
    ports:
      - "3000:80"
